FROM node:22-alpine

WORKDIR /workspace

RUN apk add --no-cache openssl

RUN corepack enable && corepack prepare pnpm@10.25.0 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json
COPY packages packages

RUN pnpm install --frozen-lockfile

COPY apps/api apps/api

WORKDIR /workspace/apps/api

RUN pnpm prisma:generate

EXPOSE 4000

CMD ["pnpm", "dev"]